datagrid:
    business-unit-grid:
        source:
            acl_resource: oro_business_unit_view
            type: orm
            query:
                select:
                    - u.id
                    - u.name
                    - u.email
                    - u.phone
                    - u.createdAt
                    - owner.name as ownerName
                    - organization.name as organizationName
                from:
                    - { table: OroOrganizationBundle:BusinessUnit, alias: u }
                join:
                    left:
                        organization:
                            join: u.organization
                            alias: organization
                        owner:
                            join: u.owner
                            alias: owner

        columns:
            id:
                type: field
            name:
                type: field
            email:
                type: field
            phone:
                type: field
            owner:
                type: field
            organization:
                type: field
            createdAt:
                type: field

        properties:
            update_link:
                type: url
                route: oro_business_unit_update
                params:
                    - id

            view_link:
                type: url
                route: oro_business_unit_view
                params:
                    - id

            delete_link:
                type: url
                route: oro_api_delete_businessunit
                params:
                    - id
        sorters:
            columns:
                id:
                    data_name: u.id
                name:
                    data_name: u.name
                email:
                    data_name: u.email
                phone:
                    data_name: u.phone
                ownerName:
                    data_name: u.ownerName
                organizationName:
                    data_name: u.organizationName
                createdAt:
                    data_name: u.createdAt

            default:
                label: %oro_grid.extension.orm_sorter.class%::DIRECTION_DESC

        filters:
            columns:
                id:
                    type: string
                    data_name: u.id
                name:
                    type: string
                    data_name: u.name
                email:
                    type: string
                    data_name: u.email
                phone:
                    type: string
                    data_name: u.phone
                ownerName:
                    type: string
                    data_name: u.ownerName
                organizationName:
                    type: string
                    data_name: u.organizationName
                createdAt:
                    type: string
                    data_name: u.createdAt

