oro_entity_config:
    ownership:
        entity:
            items:
                owner_type:
                    grid:
                        type:               options
                        label:              'Ownership Type'
                        filter_type:        oro_grid_orm_choice
                        required:           true
                        sortable:           true
                        filterable:         true
                        show_filter:        true
                        choiceOptionsProvider: 'Oro\Bundle\OrganizationBundle\Form\Type\OwnershipType::getOwnershipsArray'
                    form:
                        type:               oro_type_choice_ownership_type
                        options:
                            block:          other
                            required:       true
                            label:          'Ownership Type'

