oro_organization_bundle:
    resource:     "@OroOrganizationBundle/Controller"
    type:         annotation
    prefix:       /organization

oro_organziation_api:
    resource:     "@OroOrganizationBundle/Controller/Api/Rest/BusinessUnitController.php"
    type:         rest
    prefix:       api/rest/{version}/
    defaults:
        version:  latest
