Oro\Bundle\OrganizationBundle\Entity\Organization:
    alias:                          organization
    title_fields:                   [name]
    route:
        name:                       oro_organization_view
        parameters:
            id:                     id
    search_template:                OroOrganizationBundle:Search:organization_result.html.twig
    fields:
        -
            name:                   name
            target_type:            text
            target_fields:          [name]
