Oro\Bundle\OrganizationBundle\Entity\Organization:
    alias:                          organization
    title_fields:                   [name]
    fields:
        -
            name:                   name
            target_type:            text
            target_fields:          [name]
