Oro\Bundle\OrganizationBundle\Entity\BusinessUnit:
    alias:                          oro_business_unit
    title_fields:                   [name]
    route:
        name:                       oro_business_unit_search
        parameters:
            id:                     id
    fields:
        -
            name:                   name
            target_type:            text
            target_fields:          [name]
