parameters:
    oro_organization.type.business_unit.class:                          Oro\Bundle\OrganizationBundle\Form\Type\BusinessUnitType
    oro_organization.handler.business_unit.class:                       Oro\Bundle\OrganizationBundle\Form\Handler\BusinessUnitHandler
    oro_organization.business_unit.form.type.business_unit.api.class:   Oro\Bundle\OrganizationBundle\Form\Type\BusinessUnitApiType
    oro_organization.business_unit.manager.api.class:                   Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager
    oro_organization.business_unit.entity.class:                        Oro\Bundle\OrganizationBundle\Entity\BusinessUnit
    oro_organization.business_unit.manager.class:                       Oro\Bundle\OrganizationBundle\Entity\Manager\BusinessUnitManager
    oro_organization.type.ownership_type.class:                         Oro\Bundle\OrganizationBundle\Form\Type\OwnershipType
    oro_organization.type.form_type.class:                              Oro\Bundle\OrganizationBundle\Form\Extension\FormTypeExtension

services:
    oro_organization.form.business_unit:
        class:                        Symfony\Component\Form\Form
        factory_method:               createNamed
        factory_service:              form.factory
        arguments:                    ["oro_business_unit_form", "oro_business_unit"]

    oro_organization.form.handler.business_unit:
        class:                        %oro_organization.handler.business_unit.class%
        scope:                        request
        arguments:                    ["@oro_organization.form.business_unit", "@request", "@doctrine.orm.entity_manager"]

    oro_organization.form.type.business_unit:
        class:                        %oro_organization.type.business_unit.class%
        tags:
            - { name: form.type, alias: oro_business_unit }

    # Business Unit API
    oro_organization.business_unit.manager.api:
        class: %oro_organization.business_unit.manager.api.class%
        arguments:
            - %oro_organization.business_unit.entity.class%
            - @doctrine.orm.entity_manager

    oro_organization.form.type.business_unit.api:
        class: %oro_organization.business_unit.form.type.business_unit.api.class%
        tags:
            - { name: form.type, alias: business_unit }

    oro_organization.form.business_unit.api:
        class:                        Symfony\Component\Form\Form
        factory_method:               createNamed
        factory_service:              form.factory
        arguments:                    ["business_unit", "business_unit", null]

    oro_organization.form.handler.api:
        class:                        %oro_organization.handler.business_unit.class%
        scope:                        request
        arguments:
            - @oro_organization.form.business_unit.api
            - @request
            - @doctrine.orm.entity_manager

    oro_organization.business_unit_manager:
        class:                        %oro_organization.business_unit.manager.class%
        arguments:                    ["@doctrine.orm.entity_manager"]

    oro_entity.config.acl_config_provider:
        tags:
            - { name: oro_entity_config.provider, scope: acl }

    oro_organization.form.type.ownership_type:
        class:                        %oro_organization.type.ownership_type.class%
        arguments:                    ["@translator"]
        tags:
            - { name: form.type, alias: oro_type_choice_ownership_type }

    oro_organization.form.type.form_type:
        class:                        %oro_organization.type.form_type.class%
        tags:
            - { name: form.type_extension, alias: form }