Oro\Bundle\OrganizationBundle\Entity\BusinessUnit:
    properties:
        name:
            - NotBlank:     ~
            - Length:
                max:        255
        phone:
            - NotBlank:     ~
            - Length:
                max:        100
        email:
            - NotBlank:     ~
            - Length:
                min:        6
                max:        255
            - Email:        ~
